CREATE DATABASE IF NOT EXISTS $SQL_DATABASE;

CREATE USER IF NOT EXISTS '$SQL_USERNAME'@'%' IDENTIFIED BY '$SQL_PASSWORD';

GRANT ALL PRIVILEGES ON $SQL_DATABASE.* TO '$SQL_USERNAME'@'%';

ALTER USER 'root'@'localhost' IDENTIFIED BY '$SQL_ROOT_PASSWORD';

FLUSH PRIVILEGES;
