version: "3.8"

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "10443:10443"
      #- "443:443"
    volumes:
      - ${HOST_DATA_DIR}/www:/var/www/html:ro
      - ./requirements/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./requirements/nginx/conf/certs:/etc/nginx/certs:ro
    depends_on:
      - wordpress
    networks:
      - inception-network

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    expose:
      - "9000"
    volumes:
      - ${HOST_DATA_DIR}/www:/var/www/html
    environment:
      DB_HOST: mariadb
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      # on lira le mot de passe via secrets (voir doc plus bas)
    secrets:
      - db_password
    networks:
      - inception-network

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    volumes:
      - ${HOST_DATA_DIR}/db:/var/lib/mysql
      - ./requirements/mariadb/conf/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      # root password via secret
    secrets:
      - db_root_password
      - db_password
    networks:
      - inception-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt

networks:
  inception-network:
    driver: bridge

